"""Built-in OWASP Top 10 rule seed data.

These used to be a hardcoded regex list executed directly by the Static Scan Agent. They're now
admin-managed data (seeded here on first startup into the same rule store as Compliance Rules /
Coding Standards) so an admin can view, edit, and add to them from the UI - the agents read only
from that store (see admin_store.py / detectors/compliance_rules.py), not from this file, once seeded.
"""

SEED_OWASP_RULES: list[dict] = [
    {
        "rule_id": "OWASP-BUILTIN-001",
        "title": "Use of eval()/exec()",
        "category": "OWASP Top 10",
        "severity": "high",
        "languages": ["Python", "JavaScript", "TypeScript", "Ruby", "PHP"],
        "owasp": "A03:2021",
        "description": "Dynamic code execution via eval/exec can lead to remote code execution if input is attacker-controlled.",
        "detection": {"type": "regex", "pattern": r"\b(eval|exec)\s*\("},
        "remediation": "Avoid eval/exec on untrusted input. Use ast.literal_eval for data, or a whitelist of allowed operations.",
        "tags": ["injection", "rce"],
    },
    {
        "rule_id": "OWASP-BUILTIN-002",
        "title": "Shell Injection Risk (shell=True)",
        "category": "OWASP Top 10",
        "severity": "high",
        "languages": ["Python"],
        "owasp": "A03:2021",
        "description": "subprocess call with shell=True can allow command injection if arguments include untrusted input.",
        "detection": {"type": "regex", "pattern": r"subprocess\.[A-Za-z_]+\([^)]*shell\s*=\s*True"},
        "remediation": "Pass a list of arguments with shell=False, or use shlex.quote() if a shell is unavoidable.",
        "tags": ["injection", "command-injection"],
    },
    {
        "rule_id": "OWASP-BUILTIN-003",
        "title": "Insecure Deserialization (pickle)",
        "category": "OWASP Top 10",
        "severity": "high",
        "languages": ["Python"],
        "owasp": "A08:2021",
        "description": "pickle.loads on untrusted data can lead to arbitrary code execution.",
        "detection": {"type": "regex", "pattern": r"pickle\.loads?\("},
        "remediation": "Use a safe serialization format (JSON) for untrusted data, or cryptographically sign pickled payloads.",
        "tags": ["deserialization"],
    },
    {
        "rule_id": "OWASP-BUILTIN-004",
        "title": "Unsafe YAML Load",
        "category": "OWASP Top 10",
        "severity": "medium",
        "languages": ["Python"],
        "owasp": "A08:2021",
        "description": "yaml.load without SafeLoader can execute arbitrary Python objects from untrusted input.",
        "detection": {"type": "regex", "pattern": r"yaml\.load\((?!.*Loader\s*=\s*yaml\.SafeLoader)"},
        "remediation": "Use yaml.safe_load() (or yaml.load(data, Loader=yaml.SafeLoader)) instead.",
        "tags": ["deserialization"],
    },
    {
        "rule_id": "OWASP-BUILTIN-005",
        "title": "String-Built SQL Query",
        "category": "OWASP Top 10",
        "severity": "high",
        "languages": ["Python", "JavaScript", "TypeScript", "Java", "Go", "Ruby", "PHP", "C#"],
        "owasp": "A03:2021",
        "description": "SQL query built via string concatenation/formatting is vulnerable to SQL injection.",
        "detection": {"type": "regex", "pattern": r"(?i)(select|insert|update|delete)\s.+(%s|\+\s*[a-zA-Z_]+|f['\"])"},
        "remediation": "Use parameterized queries / prepared statements instead of building SQL via string formatting.",
        "tags": ["injection", "sql-injection"],
    },
    {
        "rule_id": "OWASP-BUILTIN-006",
        "title": "dangerouslySetInnerHTML",
        "category": "OWASP Top 10",
        "severity": "medium",
        "languages": ["JavaScript", "TypeScript"],
        "owasp": "A03:2021",
        "description": "Rendering raw HTML can lead to stored/reflected XSS if content is not sanitized.",
        "detection": {"type": "regex", "pattern": r"dangerouslySetInnerHTML"},
        "remediation": "Sanitize the HTML with a library like DOMPurify before rendering, or avoid raw HTML injection entirely.",
        "tags": ["xss"],
    },
    {
        "rule_id": "OWASP-BUILTIN-007",
        "title": "Weak Hash for Passwords",
        "category": "OWASP Top 10",
        "severity": "medium",
        "languages": ["Python", "JavaScript", "TypeScript", "Java", "Go", "Ruby", "PHP", "C#", "C", "C++"],
        "owasp": "A02:2021",
        "description": "MD5/SHA1 are unsuitable for password hashing; use bcrypt/argon2/scrypt instead.",
        "detection": {"type": "regex", "pattern": r"(?i)\b(md5|sha1)\s*\("},
        "remediation": "Replace with a password-hashing function such as bcrypt, argon2, or scrypt.",
        "tags": ["cryptography"],
    },
    {
        "rule_id": "OWASP-BUILTIN-008",
        "title": "Debug Mode Enabled",
        "category": "OWASP Top 10",
        "severity": "low",
        "languages": ["Python"],
        "owasp": "A05:2021",
        "description": "Running with debug=True in production can expose stack traces and sensitive data.",
        "detection": {"type": "regex", "pattern": r"(?i)debug\s*=\s*True"},
        "remediation": "Set debug=False in production and drive it from an environment variable instead of a literal.",
        "tags": ["misconfiguration"],
    },
]
