from collections import Counter
from datetime import datetime

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from app.schemas.analysis import Finding, ScanReport

_SEVERITY_COLORS: dict[str, tuple[int, int, int]] = {
    "critical": (178, 34, 34),
    "high": (217, 83, 26),
    "medium": (204, 153, 0),
    "low": (72, 133, 237),
    "info": (120, 120, 120),
}
_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]
_STATUS_COLORS: dict[str, tuple[int, int, int]] = {
    "completed": (39, 132, 74),
    "failed": (178, 34, 34),
    "active": (204, 153, 0),
    "pending": (120, 120, 120),
}


def _fmt_time(value: str | None) -> str:
    if not value:
        return "-"
    try:
        return datetime.fromisoformat(value).strftime("%Y-%m-%d %H:%M:%S UTC")
    except ValueError:
        return value


class _ReportPDF(FPDF):
    def header(self) -> None:
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 8, "CodeShield AI - Security Audit Report", align="L")
        self.set_x(-30)
        self.cell(20, 8, f"Page {self.page_no()}", align="R")
        self.ln(12)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, "Generated by CodeShield AI", align="C")


def _ml(pdf: FPDF, height: float, text: str) -> None:
    # multi_cell leaves the cursor at the right edge of the cell rather than resetting to the
    # left margin, so the next full-width call would compute ~0 available width otherwise.
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, height, text)


def _section_title(pdf: FPDF, title: str) -> None:
    pdf.ln(3)
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 9, f"  {title}", fill=True, ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)


def _kv_row(pdf: FPDF, label: str, value: str) -> None:
    # multi_cell's default new_x/new_y leaves the cursor at the right edge of the last line it
    # wrote (not the left margin), so without pinning x/new_x/new_y explicitly, each row after
    # the first drifts off the page and eventually leaves no horizontal space to render text.
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(50, 6, label)
    pdf.set_font("Helvetica", "", 10)
    remaining_width = pdf.w - pdf.r_margin - pdf.get_x()
    pdf.multi_cell(remaining_width, 6, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _write_cover(pdf: FPDF, repo: dict, scan: dict, report: ScanReport) -> None:
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    pdf.ln(20)
    _ml(pdf, 11, "CodeShield AI")
    pdf.set_font("Helvetica", "", 15)
    _ml(pdf, 9, "Security & Compliance Audit Report")
    pdf.ln(10)

    pdf.set_draw_color(210, 210, 210)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(8)

    _kv_row(pdf, "Repository:", repo.get("source", "-"))
    _kv_row(pdf, "Source Type:", repo.get("source_type", "-"))
    _kv_row(pdf, "Scan ID:", scan.get("scan_id", "-"))
    _kv_row(pdf, "Status:", scan.get("status", "-").upper())
    _kv_row(pdf, "Started:", _fmt_time(scan.get("started_at")))
    _kv_row(pdf, "Completed:", _fmt_time(scan.get("completed_at")))
    _kv_row(pdf, "Files Scanned:", str(report.files_scanned))
    _kv_row(pdf, "AI Reasoning Used:", "Yes" if report.used_llm else "No")
    _kv_row(pdf, "Total Findings:", str(len(report.findings)))
    pdf.ln(6)

    if report.summary:
        pdf.set_font("Helvetica", "I", 10)
        _ml(pdf, 6, report.summary)

    counts = Counter(f.severity.value for f in report.findings)
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Findings by Severity", ln=True)
    for sev in _SEVERITY_ORDER:
        n = counts.get(sev, 0)
        if n == 0:
            continue
        color = _SEVERITY_COLORS[sev]
        pdf.set_text_color(*color)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(35, 6, sev.upper())
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, str(n), ln=True)


def _write_pipeline(pdf: FPDF, scan: dict) -> None:
    _section_title(pdf, "Pipeline Execution")
    progress = scan.get("progress") or []
    if not progress:
        pdf.set_font("Helvetica", "", 10)
        _ml(pdf, 6, "No per-agent progress was recorded for this scan.")
        return

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(90, 7, "Agent / Step", border=1, fill=True)
    pdf.cell(40, 7, "Status", border=1, fill=True)
    pdf.cell(0, 7, "Completed At", border=1, fill=True, ln=True)

    pdf.set_font("Helvetica", "", 10)
    for step in progress:
        status = step.get("status", "-")
        color = _STATUS_COLORS.get(status, (0, 0, 0))
        pdf.cell(90, 7, str(step.get("agent", "-")), border=1)
        pdf.set_text_color(*color)
        pdf.cell(40, 7, status.upper(), border=1)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, _fmt_time(step.get("at")), border=1, ln=True)


def _write_compliance(pdf: FPDF, report: ScanReport) -> None:
    _section_title(pdf, "Compliance Status")
    if not report.compliance_status:
        pdf.set_font("Helvetica", "", 10)
        _ml(pdf, 6, "No compliance frameworks were evaluated for this scan.")
        return

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(90, 7, "Framework", border=1, fill=True)
    pdf.cell(40, 7, "Status", border=1, fill=True)
    pdf.cell(0, 7, "Violations", border=1, fill=True, ln=True)

    pdf.set_font("Helvetica", "", 10)
    for status in report.compliance_status:
        is_pass = status.status.lower() in {"pass", "compliant", "ok"}
        pdf.cell(90, 7, status.framework, border=1)
        pdf.set_text_color(*((39, 132, 74) if is_pass else (178, 34, 34)))
        pdf.cell(40, 7, status.status.upper(), border=1)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, str(status.violation_count), border=1, ln=True)


def _write_finding(pdf: FPDF, index: int, finding: Finding) -> None:
    color = _SEVERITY_COLORS.get(finding.severity.value, (0, 0, 0))
    location = f"{finding.file}:{finding.line}" if finding.line else finding.file

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*color)
    _ml(pdf, 7, f"{index}. [{finding.severity.value.upper()}] {finding.title}")

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "I", 9)
    _ml(pdf, 5, location)

    pdf.set_font("Helvetica", "", 10)
    _ml(pdf, 6, f"Category: {finding.category.value}    Confidence: {finding.confidence:.0%}    "
                 f"Risk Score: {finding.risk_score:.2f}")
    _ml(pdf, 6, finding.description)

    if finding.code_snippet:
        pdf.set_font("Courier", "", 8.5)
        pdf.set_fill_color(245, 245, 245)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 5, finding.code_snippet[:400], fill=True)

    if finding.exploit_explanation:
        pdf.set_font("Helvetica", "BI", 10)
        _ml(pdf, 6, "Why this is an issue:")
        pdf.set_font("Helvetica", "I", 10)
        _ml(pdf, 6, finding.exploit_explanation)

    if finding.remediation_patch:
        pdf.set_font("Helvetica", "B", 10)
        _ml(pdf, 6, "How to fix:")
        pdf.set_font("Helvetica", "", 10)
        _ml(pdf, 6, finding.remediation_patch)

    if finding.suggested_fix:
        pdf.set_font("Helvetica", "B", 10)
        status_label = {"applied": "Applied", "suggested": "Suggested, not yet applied"}.get(
            finding.fix_status, finding.fix_status
        )
        _ml(pdf, 6, f"AI-suggested code fix ({status_label}):")

        pdf.set_font("Courier", "", 8.5)
        pdf.set_fill_color(255, 235, 235)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 5, f"- {finding.suggested_fix.original_snippet}"[:400], fill=True)

        pdf.set_fill_color(230, 250, 235)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 5, f"+ {finding.suggested_fix.replacement_snippet}"[:400], fill=True)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(120, 120, 120)
        _ml(pdf, 6, "No automated fix suggestion available for this finding.")
        pdf.set_text_color(0, 0, 0)

    if finding.compliance_tags:
        pdf.set_font("Helvetica", "I", 9)
        _ml(pdf, 6, f"Compliance: {', '.join(finding.compliance_tags)}")

    pdf.set_draw_color(230, 230, 230)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 0, "", border="T", ln=True)
    pdf.ln(4)


def _write_findings(pdf: FPDF, report: ScanReport) -> None:
    _section_title(pdf, f"Findings & Suggested Fixes ({len(report.findings)})")
    if not report.findings:
        pdf.set_font("Helvetica", "", 10)
        _ml(pdf, 6, "No findings were detected in this scan.")
        return

    ordered = sorted(report.findings, key=lambda f: _SEVERITY_ORDER.index(f.severity.value)
                      if f.severity.value in _SEVERITY_ORDER else len(_SEVERITY_ORDER))
    for i, finding in enumerate(ordered, start=1):
        _write_finding(pdf, i, finding)


def build_scan_report_pdf(repo: dict, scan: dict) -> bytes:
    report = ScanReport(**(scan.get("report") or {}))

    pdf = _ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    _write_cover(pdf, repo, scan, report)

    pdf.add_page()
    _write_pipeline(pdf, scan)
    _write_compliance(pdf, report)

    pdf.add_page()
    _write_findings(pdf, report)

    return bytes(pdf.output())
